# Kubernetes Deployment Manifest for SCT Chatbot Microservice
# This file defines the deployment, service, ingress, and autoscaling configuration

---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: sct-production
  labels:
    name: sct-production
    environment: production

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sct-chatbot
  namespace: sct-production
  labels:
    app: sct-chatbot
    version: v1
    component: backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: sct-chatbot
  template:
    metadata:
      labels:
        app: sct-chatbot
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: sct-chatbot-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: chatbot
        image: acrsctprod.azurecr.io/sct-chatbot:latest  # Will be replaced by CD pipeline
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        env:
        # Azure AD Configuration
        - name: AZURE_TENANT_ID
          valueFrom:
            configMapKeyRef:
              name: chatbot-config
              key: azure-tenant-id
        - name: AZURE_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: chatbot-config
              key: azure-client-id
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: azure-client-secret
        
        # Azure OpenAI Configuration
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: chatbot-config
              key: openai-endpoint
        - name: AZURE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: openai-api-key
        - name: AZURE_OPENAI_DEPLOYMENT
          valueFrom:
            configMapKeyRef:
              name: chatbot-config
              key: openai-deployment
        
        # Microsoft Sentinel Configuration
        - name: AZURE_WORKSPACE_ID
          valueFrom:
            configMapKeyRef:
              name: chatbot-config
              key: workspace-id
        
        # Redis Configuration
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: chatbot-config
              key: redis-host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: chatbot-config
              key: redis-port
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: redis-password
        - name: REDIS_SSL
          value: "true"
        
        # Application Configuration
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        - name: WORKERS
          value: "4"
        
        # Application Insights
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: appinsights-connection-string
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /api/v1/health/ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        
        startupProbe:
          httpGet:
            path: /api/v1/health
            port: http
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 30
        
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /app/.cache
      
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - sct-chatbot
              topologyKey: kubernetes.io/hostname

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: sct-chatbot
  namespace: sct-production
  labels:
    app: sct-chatbot
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    app: sct-chatbot
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sct-chatbot
  namespace: sct-production
  labels:
    app: sct-chatbot
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://sct.azure.com"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/websocket-services: "sct-chatbot"
spec:
  tls:
  - hosts:
    - chatbot.sct.azure.com
    secretName: chatbot-tls-cert
  rules:
  - host: chatbot.sct.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sct-chatbot
            port:
              number: 80

---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sct-chatbot-hpa
  namespace: sct-production
  labels:
    app: sct-chatbot
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sct-chatbot
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max

---
# ConfigMap
# NOTE: This is a template. Replace placeholder values before deployment.
# For production, use environment-specific ConfigMaps or Kustomize overlays.
apiVersion: v1
kind: ConfigMap
metadata:
  name: chatbot-config
  namespace: sct-production
  labels:
    app: sct-chatbot
data:
  # Azure AD Configuration
  # REPLACE: Use actual Azure AD tenant and client IDs
  azure-tenant-id: "REPLACE_WITH_TENANT_ID"
  azure-client-id: "REPLACE_WITH_CLIENT_ID"
  
  # Azure OpenAI Configuration
  # REPLACE: Use actual Azure OpenAI endpoint
  openai-endpoint: "https://REPLACE_WITH_OPENAI_RESOURCE.openai.azure.com/"
  openai-deployment: "gpt-4o"
  openai-api-version: "2024-02-15-preview"
  
  # Microsoft Sentinel Configuration
  # REPLACE: Use actual workspace ID
  workspace-id: "REPLACE_WITH_WORKSPACE_ID"
  
  # Redis Configuration
  # REPLACE: Use actual Redis cache hostname
  redis-host: "REPLACE_WITH_REDIS_HOST.redis.cache.windows.net"
  redis-port: "6380"
  
  # Application Configuration
  environment: "production"
  log-level: "INFO"
  app-version: "1.0.0"

---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sct-chatbot-sa
  namespace: sct-production
  labels:
    app: sct-chatbot
  annotations:
    azure.workload.identity/client-id: "your-workload-identity-client-id"

---
# Network Policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sct-chatbot-netpol
  namespace: sct-production
spec:
  podSelector:
    matchLabels:
      app: sct-chatbot
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8000
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443  # HTTPS
    - protocol: TCP
      port: 6380  # Redis SSL
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53  # DNS

---
# Pod Disruption Budget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sct-chatbot-pdb
  namespace: sct-production
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: sct-chatbot
